CREATE TABLE IF NOT EXISTS  LOGINUSUARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CORREO VARCHAR(200) NOT NULL UNIQUE,
	PASSWORD VARCHAR(300) NOT NULL,
	NOMBRE VARCHAR(200) NOT NULL,
	ROLE VARCHAR(200) NOT NULL
);
INSERT INTO LOGINUSUARIO (CORREO, PASSWORD, NOMBRE, ROLE) VALUES ('edison@gmail.com','$2a$10$XsxL7X62GvmQ8biGie/XcuOVQ92wN1UIow2go.hRfLOPOUHcD46JK','edisonzamora','ADM');
INSERT INTO LOGINUSUARIO (CORREO, PASSWORD, NOMBRE, ROLE) VALUES ('edison2@gmail.com','$2a$10$XsxL7X62GvmQ8biGie/XcuOVQ92wN1UIow2go.hRfLOPOUHcD46JK','edisonzamora_2','USU');
INSERT INTO LOGINUSUARIO (CORREO, PASSWORD, NOMBRE, ROLE) VALUES ('edison3@gmail.com','$2a$10$XsxL7X62GvmQ8biGie/XcuOVQ92wN1UIow2go.hRfLOPOUHcD46JK','edisonzamora_3','USU');
